var recepty = {
cukrovinky: {
anglicky_chlebicek:'Anglický chlebíček',
anyzove_kornoutky:'Anýzové kornoutky',
anyzove_preclicky:'Anýzové preclíčky',
anyzovy_chlebicek:'Anýzový chlebíček',
bila_jitrnice_z_misenskych_jablek:'Bílá jitrnice z míšeňských jablek',
biskupsky_chlebicek:'Biskupský chlebíček',
cerne_piskoty:'Černé piškoty',
citronove_hromadky:'Citronové hromádky',
citronove_loucky:'Citronové loučky',
cokoladove_venecky_nebo_hubinky:'Čokoládové věnečky nebo hubinky',
cukrovane_mandle:'Cukrované mandle',
cukrova_sunka:'Cukrová šunka',
cukrova_zemcatka:'Cukrová zemčátka',
cukrovy_cervulat:'Cukrový cervulát',
cukrovy_had:'Cukrový had',
dorticky_zloutkove:'Dortičky žloutkové',
hnede_mandlove_obloucky:'Hnědé mandlové obloučky',
hubinky_z_liskovych_orisku:'Hubinky z lískových oříšků',
chleba_s_maslem:'Chleba s máslem',
chlebicek_z_kastanu:'Chlebíček z kaštanů',
janovske_kvadratky:'Janovské kvadrátky',
jeste_jine_loucky_z_mandli:'Ještě jiné loučky z mandlí',
jine_horke_pokroutky:'Jiné hořké pokroutky',
jine_loucky_z_mandli:'Jiné loučky z mandlí',
jine_ocukrovane_kastany:'Jiné ocukrované kaštany',
komisni_chlebicek:'Komisní chlebíček',
kralovsky_chlebicek:'Královský chlebíček',
ledove_koblizky:'Ledové kobližky',
lihove_venecky:'Lihové věnečky',
mandlove_hubinky:'Mandlové hubinky',
mandlove_koblizky_s_rybizem:'Mandlové kobližky s rybízem',
mandlove_obloucky:'Mandlové obloučky',
mandlove_obloucky_na_jiny_zpusob:'Mandlové obloučky na jiný způsob',
mandlove_rizky:'Mandlové řízky',
mandlove_tasky:'Mandlové tašky',
mandlove_venecky:'Mandlové věnečky',
mandlovy_chlebicek:'Mandlový chlebíček',
merunkove_preclicky:'Meruňkové preclíčky',
michane_koblihy:'Míchané koblihy',
obloucky:'Obloučky',
ocukrovane_amarelky:'Ocukrované amarelky',
ocukrovane_datle:'Ocukrované datle',
ocukrovane_kastany:'Ocukrované kaštany',
ocukrovane_orisky:'Ocukrované oříšky',
ocukrovane_pomerance:'Ocukrované pomeranče',
oplatky:'Oplatky',
piskoty:'Piškoty',
pokroutky_z_horkych_mandli:'Pokroutky z hořkých mandlí',
preclicky_z_pistacii:'Preclíčky z pistácií',
pulmesicky_z_velkych_orechu:'Půlměsíčky z velkých ořechů',
skoricove_pokroutky:'Skořicové pokroutky',
skoricove_venecky:'Skořicové věnečky',
smazene_mandle:'Smažené mandle',
spanelske_vetry_a_mandlemi:'Španělské větry a mandlemi',
spanelske_vetry_se_zavareninkou:'Španělské větry se zavařeninkou',
spanelsky_chlebicek:'Španělský chlebíček',
uhersky_chlebicek:'Uherský chlebíček',
vandlicky_dortove:'Vandličky dortové',
vanilove_hubinky:'Vanilové hubinky',
venecky_z_cokolady:'Věnečky z čokolády',
vselike_drobnustky_z_maselneho_testa:'Všeliké drobnůstky z máselného těsta',
zavitek_z_piskotoveho_testu:'Závitek z piškotového těstu'
},

dodatek:{
jak_se_da_zeleny_hrasek_na_zimu_zachovat:'Jak se dá zelený hrášek na zimu zachovat',
jak_se_dela_jecna_mouka:'Jak se dělá ječná mouka',
jak_se_delaji_jaternice_jelita_a_klobasy:'Jak se dělají jaternice, jelita a klobásy',
jak_se_dela_rejzova_mouka_a_krupice:'Jak se dělá rejžová mouka a krupice',
jak_se_maji_houby_susit:'Jak se mají houby sušit',
jak_se_maji_vejce_ukladat_aby_se_nepokazily:'Jak se mají vejce ukládat, aby se nepokazily',
jak_se_maslo_naklada_soli_a_prevaruje:'Jak se máslo nakládá, solí a převařuje',
jak_se_maso_k_uzeni_naklada:'Jak se maso k uzení nakládá',
jak_se_ma_v_postni_dni_tabule_zridit:'Jak se má v postní dni tabule zřídit',
jak_se_mejdlovy_a_kafrovy_lih_pro_domaci_potreba_pripravuje:'Jak se mejdlový a kafrový líh pro domácí potřeba připravuje',
jak_se_povidla_vareji:'Jak se povidla vařejí',
jak_se_pripalena_smetana_opet_napravi:'Jak se připálená smetana opět napraví',
jak_se_zeli_naklada:'Jak se zelí nakládá',
jak_se_zmrzle_vejce_nebo_jablka_zase_napravi:'Jak se zmrzlé vejce nebo jablka zase napraví',
jaternice:'Jaternice',
jelita:'Jelita',
klobasy:'Klobásy',
kterak_se_pri_mensich_i_vetsich_hostinach_tabule_upravovati_maji:'Kterak se při menších i větších hostinách tabule upravovati mají',
rychly_prostredek_kdyz_se_kucharka_spali_neb_opari:'Rychlý prostředek, když se kuchařka spálí neb opaří'
},

dorty:{
cerny_dort_se_zavareninkou:'Černý dort se zavařeninkou',
cerny_chlebovy_dort:'Černý chlebový dort',
dobry_skladany_dort:'Dobrý skládaný dort',
dort_cokoladovy:'Dort čokoládový',
dort_kastanovy:'Dort kaštanový',
dort_maslovy_nebo_listkovy:'Dort máslový nebo lístkový',
dort_mechovy:'Dort mechový',
dort_mramorovy:'Dort mramorový',
dort_piskotovy:'Dort piškotový',
dort_rosolovany_z_jablek:'Dort rosolovaný z jablek',
dort_rybizovy:'Dort rybízový',
dort_se_smetanovou_penou:'Dort se smetanovou pěnou',
dort_z_koreni:'Dort z koření',
dort_z_liskovych_orisku:'Dort z lískových oříšků',
dort_z_maku:'Dort z máku',
dort_z_nudli:'Dort z nudlí',
chlebovy_dort_bez_mandli:'Chlebový dort bez mandli',
jiny_mandlovy_dort:'Jiný mandlový dort',
jiny_orechovy_dort:'Jiný ořechový dort',
linecky_dort:'Linecký dort',
linecky_dort_na_jiny_zpusob:'Linecký dort na jiný způsob',
mandlovy_dort:'Mandlový dort',
piskotovy_dort_se_zavareninkou:'Piškotový dort se zavařeninkou',
pomerancovy_dort_na_jiny_zpusob:'Pomerančový dort na jiný způsob',
pomerancovy_dort:'Pomerančový dort',
prazeny_dort_z_mandli:'Pražený dort z mandlí',
vencovy_dort_z_mandli:'Věncový dort z mandlí',
zajeci_dort:'Zaječí dort',
zemcatovy_dort:'Zemčatový dort'
},

hovezi_maso_a_rozlicna_jeho_uprava:{
beefsteak_aneb_hovezi_rizky:'Beefsteak aneb hovězí řízky',
beefsteak_na_cerstvy_zpusob:'Beefsteak na čerstvý způsob',
beefsteak_se_sardelemi:'Beefsteak se sardelemi',
dusene_hovezi_maso:'Dušené hovězí maso',
dusene_hovezi_maso_na_jiny_zpusob:'Dušené hovězí maso na jiný způsob',
fasirovany_rostenec:'Fašírovaný roštěnec',
fasirovany_rostenec_na_jiny_zpusob:'Fašírovaný roštěnec na jiný způsob',
gulas:'Gulaš',
gulas_na_jiny_zpusob:'Gulaš na jiný způsob',
hovezi_jazyk_na_rozni_peceny:'Hovězí jazyk na rožni pečený',
hovezi_jazyk_se_sardelovou_omackou:'Hovězí jazyk se sardelovou omáčkou',
hovezi_jazyk_s_polskou_omackou:'Hovězí jazyk s polskou omáčkou',
hovezi_ledvinky:'Hovězí ledvinky',
hovezi_maso_se_zazvorem:'Hovězí maso se zázvorem',
hovezi_ohon:'Hovězí ohon',
karbanatky_ze_svickove_pecene:'Karbanátky ze svíčkové pečeně',
nadivany_hovezi_jazyk:'Nadívaný hovězí jazyk',
obycejne_hovezi_maso:'Obyčejné hovězí maso',
peceny_hovezi_jazyk:'Pečený hovězí jazyk',
rostenec_na_francouzsky_zpusob:'Roštěnec na francouzský způsob',
rostenec:'Roštěnec',
rostenec_s_kyselou_smetanou:'Roštěnec s kyselou smetanou',
sekane_rizky_z_hoveziho_masa:'Sekané řízky z hovězího masa',
svickova_nebo_jina_hovezi_pecene:'Svíčková nebo jiná hovězí pečeně',
svickova_pecene_jeste_na_jiny_zpusob:'Svíčková pečeně ještě na jiný způsob',
svickova_pecene_na_jiny_zpusob:'Svíčková pečeně na jiný způsob',
tak_nazvana_svickova_pecene:'Tak nazvaná svíčková pečeně'
},

jeste_nektera_postni_jidla:{
houbovec:'Houbovec',
houbovec_se_zemcatky:'Houbovec se zemčátky',
jina_miseninka_z_ryb:'Jiná míšeninka z ryb',
karbanatky_a_klobasy_z_kapra:'Karbanátky a klobásy z kapra',
koblihy_ze_zemcat:'Koblihy ze zemčat',
kraplicky_s_kaprovym_mlecim:'Krapličky s kaprovým mlečím',
meridon_z_raku:'Meridon z raků',
miseninka_z_ryb:'Míšeninka z ryb',
omeletky_se_sardelemi:'Omeletky se sardelemi',
postni_pastycky:'Postní pastyčky',
postni_topinky:'Postní topinky',
puding_do_stiky:'Puding do štiky',
raci_koblizky:'Račí kobližky',
rakovy_puding:'Rakový puding',
smazeni_raci:'Smažení raci',
smazeny_tvaroh_z_raku:'Smažený tvaroh z raků',
svitek_ze_suchych_hub:'Svítek ze suchých hub',
tvarohove_koblihy:'Tvarohové koblihy',
vandlicky_rakove_na_jiny_zpusob:'Vandličky rakové na jiný způsob',
vandlicky_rakove:'Vandličky rakové',
vandlicky_rakove_z_krupice:'Vandličky rakové z krupice',
zajic_z_ryb:'Zajíc z ryb',
zemcata_a_vejcemi:'Zemčata a vejcemi'
},

kolace_buchty_rozlicne_jine_pecivo_a_pamlsky:{
bilkove_kolace:'Bílkové koláče',
bily_norimbersky_pernik:'Bílý norimberský perník',
bozi_milosti:'Boží milosti',
celtlicky_z_koreni:'Celtličky z kořeni',
cerny_norimbersky_pernik:'Černý norimberský perník',
cerstve_sucharky:'Čerstvé suchárky',
ceske_kolace:'České koláče',
cisarska_buchta:'Císařská buchta',
dobra_buchta:'Dobrá buchta',
dobre_a_lacine_rohlicky_ku_kave:'Dobré a laciné rohlíčky ku kávě',
dobre_preclicky:'Dobré preclíčky',
dobry_pernik:'Dobrý perník',
dobry_tvarohovy_kolac:'Dobrý tvarohový koláč',
dulkove_kolace:'Důlkové koláče',
francouzsky_pernik:'Francouzský perník',
hanoversky_kolac:'Hanoverský koláč',
hradecke_preclicky:'Hradecké preclíčky',
jine_ceske_kolace:'Jiné české koláče',
jine_dobre_preclicky:'Jiné dobré preclíčky',
jine_koblihy:'Jiné koblihy',
jine_tycky_k_caji:'Jiné tyčky k čaji',
jiny_kolac_se_svestkami:'Jiný koláč se švestkami',
karlovarske_kolace:'Karlovarské koláče',
kminem_sypane_rohlicky_k_pivu:'Kmínem sypané rohlíčky k pivu',
koblihy:'Koblihy',
koblizky_z_paleneho_testa:'Kobližky z páleného těsta',
kolac_a_jablkami:'Koláč a jablkami',
kolace_zloutkove:'Koláče žloutkové',
kolacky_s_korenim:'Koláčky s kořením',
kolac_se_svestkami:'Koláč se švestkami',
kolac_se_tresnemi:'Koláč se třešněmi',
krehke_martinske_rohliky:'Křehké martinské rohlíky',
krehke_preclicky_s_anyzem:'Křehké preclíčky s anýzem',
krehky_kolac_s_kremem:'Křehký koláč s krémem',
kuneticke_preclicky:'Kunětické preclíčky',
male_nadivane_buchticky:'Malé nadívané buchtičky',
male_suchary:'Malé suchary',
malinke_preclicky_k_caji:'Malinké preclíčky k čaji',
mandlove_trubicky:'Mandlové trubičky',
marcipanky:'Marcipánky',
marcipanky_na_jiny_zpusob:'Marcipánky na jiný způsob',
moravsky_kolac_s_visnemi:'Moravský koláč s višněmi',
mourenin_benatsky:'Mouřenín benátský',
nemecke_kolace:'Německé koláče',
obycejne_preclicky_ku_kave:'Obyčejné preclíčky ku kávě',
oplatky:'Oplatky',
parizske_rizky:'Pařížské řízky',
sisky:'Šišky',
skoricove_trubicky_ii:'Skořicové trubičky II',
skoricove_trubicky:'Skořicové trubičky',
slane_preclicky:'Slané preclíčky',
spesne_rohlicky:'Spěšné rohlíčky',
sucharky_k_vinu:'Suchárky k vínu',
suchary:'Suchary',
svedsky_chlebicek:'Švédský chlebíček',
trena_buchta_bez_smetany:'Třená buchta bez smetany',
trena_buchta:'Třená buchta',
tycky_k_caji:'Tyčky k čaji',
vanocka:'Vánočka',
velikonocni_mazanec:'Velikonoční mazanec',
velke_kolace_ku_kave:'Velké koláče ku kávě',
visnovy_kolac_pokryty:'Višňový koláč pokrytý',
zazvorky:'Zázvorky',
zmrzle_kolace:'Zmrzlé koláče'
},

kompoty:{
jiny_kompot_z_cerstvych_svestek:'Jiný kompot z čerstvých švestek',
jiny_kompot_z_misenskych_jablek:'Jiný kompot z míšeňských jablek',
kompot_kastanovy:'Kompot kaštanový',
kompot_z_angrestu:'Kompot z angreštu',
kompot_z_broskvi:'Kompot z broskvi',
kompot_z_brusinek:'Kompot z brusinek',
kompot_z_cerstvych_jablek:'Kompot z čerstvých jablek',
kompot_z_cerstvych_svestek:'Kompot z čerstvých švestek',
kompot_z_cerstvych_visni:'Kompot z čerstvých višní',
kompot_ze_gdoulovych_jablek:'Kompot ze gdoulových jablek',
kompot_ze_suchych_svestek_a_ze_sipku:'Kompot ze suchých švestek a ze šípků',
kompot_z_hrusek:'Kompot z hrušek',
kompot_z_jahod:'Kompot z jahod',
kompot_z_malin:'Kompot z malin',
kompot_z_melounu:'Kompot z melounu',
kompot_z_merunek:'Kompot z meruněk',
kompot_z_mirabelek:'Kompot z mirabelek',
kompot_z_misenskych_jablek:'Kompot z míšeňských jablek',
kompot_z_mrkve_a_pomerancu:'Kompot z mrkve a pomerančů',
kompot_z_mrkve:'Kompot z mrkve',
smazeny_kompot:'Smažený kompot',
},

ledy_rozlicnych_barev:{
bily_led:'Bílý led',
cerny_led:'Černý led',
citronovy_a_pomerancovy_led:'Citronový a pomerančový led',
jahodovy_led:'Jahodový led',
jak_se_cukrova_krupice_pripravuje_a_barvi:'Jak se cukrová krupice připravuje a barví',
ruzovy_led:'Růžový led',
skoricovy_led:'Skořicový led',
vareny_cukr_na_okrasleni_dortu:'Vařený cukr na okrášlení dortů',
vareny_cukr_vselijakych_barev:'Vařený cukr všelijakých barev',
vodni_led:'Vodní led',
zeleny_led:'Zelený led',
zluty_led:'Žlutý led'
},

masite_rosoly:{
aspik:'Aspik',
husi_jatra_v_rosolu:'Husí játra v rosolu',
huspenina_z_hovezich_paznehtu:'Huspenina z hovězích paznehtů',
kanci_hlava_v_rosolu:'Kančí hlava v rosolu',
kapoun_v_rosolu:'Kapoun v rosolu',
krocan_v_rosolu:'Krocan v rosolu',
kurata_v_rosolu:'Kuřata v rosolu',
nadivane_sele_v_rosolu:'Nadívané sele v rosolu',
nadivany_kapoun_s_aspikem:'Nadívaný kapoun s aspikem',
puding_z_koroptvi_v_aspiku:'Puding z koroptví v aspiku',
rizky_ze_studeneho_masa:'Řízky ze studeného masa',
rizky_ze_zajice_v_rosolu:'Řízky ze zajíce v rosolu',
rosolovane_selatko:'Rosolované selátko',
rosolovany_tetrev:'Rosolovaný tetřev',
rosol_z_teleci_hlavy_a_z_nozicek:'Rosol z telecí hlavy a z nožiček',
stocene_sele_s_rosolem:'Stočené sele s rosolem',
studena_hlava_divokeho_kance:'Studená hlava divokého kance',
studena_veprova_hlava:'Studená vepřová hlava',
studeny_kapoun_aneb_krocan_v_omacce:'Studený kapoun aneb krocan v omáčce',
teleci_frikando_s_aspikem:'Telecí frikandó s aspikem',
teleci_mozky_v_aspiku:'Telecí mozky v aspiku',
teleci_rizky_v_rosolu:'Telecí řízky v rosolu'
},

moucna_jidla_obycejna_i_jemnejsi:{
bublanina_svestkova:'Bublanina švestková',
bublanina_visnova:'Bublanina višňová',
buchticky_s_kremem:'Buchtičky s krémem',
dobra_strudle_s_tvarohem:'Dobrá štrudle s tvarohem',
flicky_se_sunkou:'Flíčky se šunkou',
flicky_s_jablkami:'Flíčky s jablkami',
flicky_s_rakami:'Flíčky s rakami',
hrachove_livanecky:'Hrachové lívanečky',
jablka_v_zupanu:'Jablka v županu',
jablkovec:'Jablkovec',
jidlo_oplatkove:'Jídlo oplatkové',
jine_moucne_knedliky:'Jiné moučné knedlíky',
knedlicky_ve_smetane:'Knedlíčky ve smetaně',
knedliky_se_slaninou:'Knedlíky se slaninou',
kraple_se_spenatem:'Kraple se špenátem',
kraple_s_povidlami:'Kraple s povidlami',
krupicne_knedlicky_v_kremu:'Krupičné knedlíčky v krému',
krupicne_knedliky:'Krupičné knedlíky',
lite_smazene_strudle:'Lité smažené štrudle',
lite_strudle_cili_omeletky_s_povidlami:'Lité štrudle čili omeletky s povidlami',
lite_strudle_s_cokoladou:'Lité štrudle s čokoládou',
lite_strudle_s_miseninkou:'Lité štrudle s míšeninkou',
lite_strudle_s_tvarohem:'Lité štrudle s tvarohem',
lite_zelnicky:'Lité zelníčky',
makaronky:'Makaronky',
moucne_knedliky:'Moučné knedlíky',
moucne_livanecky:'Moučné lívanečky',
nudle_s_jablkami:'Nudle s jablkami',
nudle_s_mandlemi:'Nudle s mandlemi',
nudle_smazene:'Nudle smažené',
nudle_s_rakami:'Nudle s rakami',
nudle_s_tvarohem:'Nudle s tvarohem',
nudle_ve_smetane:'Nudle ve smetaně',
polenta:'Polenta',
prazena_kase:'Pražená kaše',
rakove_strudle:'Rakové štrudle',
rejze_pecena_se_sekaninou:'Rejže pečená se sekaninou',
rejze_s_jablkami_ii:'Rejže s jablkami II',
rejze_s_jablkami:'Rejže s jablkami',
rejze_s_uzenym_masem:'Rejže s uzeným masem',
rejzova_kase:'Rejžová kaše',
smazenec_chlebovy:'Smaženec chlebový',
smazenec_krupicny:'Smaženec krupičný',
smazenec_s_vanilovou_smetanou:'Smaženec s vanilovou smetanou',
smazenec_ze_zemlicky:'Smaženec ze žemličky',
smazenec_z_mouky:'Smaženec z mouky',
smazene_nudle_nebo_rejze:'Smažené nudle nebo rejže',
svestkove_knedliky_s_kvasnicemi:'Švestkové knedlíky s kvasnicemi',
svestkove_knedliky:'Švestkové knedlíky',
svitek_krupicny:'Svítek krupičný',
svitek_z_mrkve:'Svítek z mrkve',
svitek_z_vina:'Svitek z vina',
tasky_s_tvarohem:'Tašky s tvarohem',
tazena_strndle_s_jablkami:'Tažená štrndle s jablkami',
tazena_strudle_na_jiny_zpusob_se_zemlickou:'Tažená štrudle na jiný způsob se žemličkou',
tazena_strudle_s_telecimi_plicemi:'Tažená štrudle s telecími plícemi',
tazena_strudle_s_visnemi:'Tažená štrudle s višněmi',
tresnovec:'Třešňovec',
turecke_knedlicky:'Turecké knedlíčky',
turecky_turban:'Turecký turban',
tvarohove_knedliky:'Tvarohové knedlíky',
tvarohove_slejsky:'Tvarohové šlejšky',
valena_strudle_s_jablkami:'Válená štrudle s jablkami',
valena_strudle_s_rejzi:'Válená štrudle s rejži',
varena_buchta_se_slaneckem:'Vařená buchta se slanečkem',
zelne_slejsky:'Zelné šlejšky',
zelne_svitky:'Zelné svítky',
zelniky_bez_kvasnic:'Zelníky bez kvasnic',
zelniky:'Zelníky',
zemcatove_knedliky_na_jiny_zpusob:'Zemčatové knedlíky na jiný způsob',
zemcatove_knedliky:'Zemčatové knedlíky',
zemcatove_slejsky:'Zemčatové šlejšky',
zemcatove_zavitky_s_uzeninou:'Zemčatové závitky s uzeninou',
zemlickove_jidlo_s_rumem:'Žemličkové jídlo s rumem',
zemlickove_nadivane_livanecky:'Žemličkové nadívané lívanečky',
zemlickove_rizky_s_hovezim_tokem:'Žemličkové řízky s hovězím tokem',
zemlickovy_svitek_s_povidlami:'Žemličkový svítek s povidlami',
zemlicky_nadivane:'Žemličky nadívané',
zemlicky_s_povidlami:'Žemličky s povidlami',
zemlovka_s_hrozinkami:'Žemlovka s hrozinkami'
},

nadivky_do_kolacu_buchticek_a_koblih:{
cukrova_jiska:'Cukrová jíška',
hrozinkova_povidla:'Hrozinková povidla',
jicha_k_posypani_kolacu:'Jícha k posypání koláčů',
mak:'Mák',
pernik:'Perník',
povidla:'Povidla',
snih:'Sníh',
tvaroh:'Tvaroh'
},

nakypy:{
bilkove_venecky_se_sodo:'Bílkové věnečky se šodó',
citronove_sodo:'Citronové šodó',
cokoladovy_krem_s_rejzi:'Čokoládový krém s rejží',
cokoladovy_nakyp_na_jiny_zpusob:'Čokoládový nákyp na jiný způsob',
cokoladovy_nakyp_s_vinni_penou:'Čokoládový nákyp s vinní pěnou',
dobry_nakyp_ze_smazene_zemlicky:'Dobrý nákyp ze smažené žemličky',
dortove_vandlicky_se_sodo:'Dortové vandličky se šodó',
horici_jitrnicky:'Hořící jitrničky',
chlebovy_nakyp_jeste_na_jiny_zpusob:'Chlebový nákyp ještě na jiný způsob',
jeste_jiny_nakyp_z_jablek:'Ještě jiný nákyp z jablek',
jine_vandlicky_se_sodo:'Jiné vandličky se šodó',
jiny_citronovy_nakyp:'Jiný citronový nákyp',
jiny_chlebovy_nakyp:'Jiný chlebový nákyp',
jiny_mandlovy_nakyp:'Jiný mandlový nákyp',
jiny_nakyp_ze_smazene_zemlicky:'Jiný nákyp ze smažené žemličky',
jiny_nakyp_z_jablek:'Jiný nákyp z jablek',
jiny_piskotovy_nakyp:'Jiný piškotový nákyp',
jiny_zemcatovy_nakyp:'Jiný zemčatový nákyp',
kosicky_se_sodo:'Košíčky se šodó',
krem_cokoladovy:'Krém čokoládový',
krem_kavovy:'Krém kávový',
krem:'Krém',
krem_s_cukrovinkami:'Krém s cukrovinkami',
krem_s_rumem_aneb_maraskinem:'Krém s rumem aneb maraskinem',
krem_vanilovy:'Krém vanilový',
krupicne_venecky_s_kremem:'Krupičné věnečky s krémem',
mandlovy_nakyp_jeste_na_jiny_zpusob:'Mandlový nákyp ještě na jiný způsob',
merunkovy_nakyp_v_plamenu:'Meruňkový nákyp v plamenu',
moravsky_cokoladovy_nakyp:'Moravský čokoládový nákyp',
moucny_nakyp_s_cokoladou:'Moučný nákyp s čokoládou',
nadivany_mandlovy_nakyp:'Nadívaný mandlový nákyp',
nakyp_cokoladovy:'Nákyp čokoládový',
nakyp_jablkovy_s_piskotami:'Nákyp jablkový s piškotami',
nakyp_jahodovy:'Nákyp jahodový',
nakyp_jiskovy:'Nákyp jíškový',
nakyp_kastanovy:'Nákyp kaštanový',
nakyp_krupicny_s_mandlemi:'Nákyp krupičný s mandlemi',
nakyp_malinovy:'Nákyp malinový',
nakyp_mandlovy_s_tvrdymi_zloutky:'Nákyp mandlový s tvrdými žloutky',
nakyp_merunkovy:'Nákyp meruňkový',
nakyp_nudlovy_s_cokoladou:'Nákyp nudlový s čokoládou',
nakyp_rakovy:'Nákyp rakový',
nakyp_rejzovy_s_nadivanymi_jablkami:'Nákyp rejžový s nadívanými jablkami',
nakyp_se_smazenymi_nudlemi:'Nákyp se smaženými nudlemi',
nakyp_spenatovy:'Nákyp špenátový',
nakyp_s_piskotami_nebo_s_vanilovymi_kabinkami:'Nákyp s piškotami nebo s vanilovými kabinkami',
nakyp_s_racim_maslem:'Nákyp s račím máslem',
nakyp_studeny:'Nákyp studený',
nakyp_tvarohovy:'Nákyp tvarohový',
nakyp_zapaleny:'Nákyp zapálený',
nakyp_zemcatovy:'Nákyp zemčatový',
nakyp_ze_sodo:'Nákyp ze šodó',
nakyp_ze_strouhaneho_chleba:'Nákyp ze strouhaného chleba',
nakyp_ze_strouhanky:'Nákyp ze strouhanky',
nakyp_z_hoveziho_tuku:'Nákyp z hovězího tuku',
nakyp_z_jablek:'Nákyp z jablek',
nakyp_z_kapaneho_testa:'Nákyp z kapaného těsta',
nakyp_z_kaproveho_mleci:'Nákyp z kaprového mléčí',
nakyp_z_kavy:'Nákyp z kávy',
nakyp_z_krup:'Nákyp z krup',
nakyp_z_kysele_smetany:'Nákyp z kyselé smetany',
nakyp_z_mandli:'Nákyp z mandlí',
nakyp_z_omeletek:'Nákyp z omeletek',
nakyp_z_prazeneho_cukru:'Nákyp z praženého cukru',
nakyp_z_rejze:'Nákyp z rejže',
nakyp_z_rejzove_krupice:'Nákyp z rejžové krupice',
nakyp_z_tvrdych_zloutku:'Nákyp z tvrdých žloutku',
nakyp_z_vareneho_citronu:'Nákyp z vařeného citronu',
omeletky_se_sodo:'Omeletky se šodó',
omeletky_s_jablkami:'Omeletky s jablkami',
peceny_krem:'Pečený krém',
piskotovy_nakyp_s_mandlemi:'Piškotový nákyp s mandlemi',
piskoty_se_sodo:'Piškoty se šodó',
piskoty_se_zavareninkou:'Piškoty se zavařeninkou',
smazene_jablkove_venecky:'Smažené jablkové věnečky',
smazene_svestky:'Smažené švestky',
smazene_zavitky_s_jahodami:'Smažené závitky s jahodami',
snekovy_kopecek:'Šnekový kopeček',
spanelske_vetry_se_sodo:'Španělské větry se šodó',
spesny_nakyp_z_jablek:'Spěšný nákyp z jablek',
strakaty_nakyp:'Strakatý nákyp',
venec_z_paleneho_testa:'Věnec z páleného těsta'
},

nalozeniny_k_hovezimu_masu:{
male_okurcicky_v_pare_nalozene:'Malé okurčičky v páře naložené',
nalozena_cervena_repa:'Naložená červená řepa',
nalozena_michaninka:'Naložená míchaninka',
nalozene_bobove_lusky:'Naložené bobové lusky',
nalozene_brusinky:'Naložené brusinky',
nalozene_hribky:'Naložené hříbky',
nalozene_ryzce:'Naložené ryzce',
okurky_oloupane:'Okurky oloupané',
okurky_ve_vode_nalozene:'Okurky ve vodě naložené',
okurky_v_octe_nalozene:'Okurky v octě naložené',
ryzce_v_parnich_sklenicich_nalozene:'Ryzce v parních sklenicích naložené'
},

napoje:{
bisof:'Bišof',
caj:'Čaj',
cajovy_puns:'Čajový punš',
citronova_voda:'Citronová voda',
cokolada:'Čokoláda',
cokolada_z_vody:'Čokoláda z vody',
grog:'Grog',
jecna_voda:'Ječná voda',
kava:'Káva',
malinova_stava:'Malinová šťáva',
mandlove_mleko:'Mandlové mléko',
napoj_na_zpusob_likeru:'Nápoj na způsob likéru',
palene_vino:'Pálené víno',
punc_s_vejcemi:'Punč s vejcemi',
puns:'Punš',
puns_se_sampanskym_vinem:'Punš se šampaňským vínem',
rejzovka:'Rejžovka',
sodo:'Šodó',
sodo_ze_slivovice:'Šodó ze slivovice',
studeny_puns:'Studený punš'
},

omacky_k_hovezimu_masu:{
cibulova_omacka_s_vinem:'Cibulová omáčka s vínem',
horcice:'Hořčice',
kren_kysely:'Křen kyselý',
kren_polivkovy:'Křen polívkový',
kren_smetanovy:'Křen smetanový',
kysely_rosol:'Kyselý rosol',
omacka_cibulkova:'Omáčka cibulková',
omacka_kaprlova:'Omáčka kaprlová',
omacka_koprova:'Omáčka koprová',
omacka_mejonezova:'Omáčka mejonézová',
omacka_na_holandsky_zpusob:'Omáčka na holandský způsob',
omacka_polska:'Omáčka polská',
omacka_sardelova:'Omáčka sardelová',
omacka_s_kyselou_smetanou:'Omáčka s kyselou smetanou',
omacka_z_angrestu:'Omáčka z angreštu',
omacka_z_cerstve_okurky:'Omáčka z čerstvé okurky',
omacka_ze_suchych_hub:'Omáčka ze suchých hub',
omacka_ze_zampionu:'Omáčka ze žampionů',
omacka_z_kerblika:'Omáčka z kerblíka',
omacka_z_koreni:'Omáčka z koření',
omacka_z_korinku_od_zelenin:'Omáčka z kořínků od zelenin',
omacka_z_nalozene_okurky:'Omáčka z naložené okurky',
omacka_z_rajskych_jablek:'Omáčka z rajských jablek',
omacka_z_ryzcu:'Omáčka z ryzců',
studena_omacka_ku_zverine:'Studená omáčka ku zvěřině',
studena_omacka:'Studená omáčka',
zlata_cibulova_omacka:'Zlatá cibulová omáčka'
},

ovocni_zavareninky:{
boruvky_zavarene:'Borůvky zavařené',
jablkova_zavareninka:'Jablková zavařeninka',
jahodova_zavareninka:'Jahodová zavařeninka',
jina_jablkova_zavareninka:'Jiná jablková zavařeninka',
malinova_zavareninka:'Malinová zavařeninka',
merunkova_zavareninka:'Meruňková zavařeninka',
oloupane_svestky_vyvarene:'Oloupané švestky vyvařené',
rybizova_stava_za_studena_pripravena:'Rybízová šťáva za studena připravená',
rybizova_zavareninka_procezena:'Rybízová zavařeninka procezená',
rybizova_zavareninka:'Rybízová zavařeninka',
sipkova_zavareninka:'Šípková zavařeninka',
stava_z_dristalek:'Šťáva z dřišťálek',
syr_z_gdoulovych_jablek:'Sýr z gdoulových jablek',
tresnova_zavareninka:'Třešňová zavařeninka',
visnova_stava:'Višňová šťáva',
visnova_zavareninka:'Višňová zavařeninka',
visnovka:'Višňovka',
zavareninka_z_amarelek:'Zavařeninka z amarelek',
zavareninka_z_dristalek:'Zavařeninka z dřišťálek',
zavareninka_z_gdoulovych_jablek:'Zavařeninka z gdoulových jablek'
},

pastyky:{
jiny_zpusob_masloveho_testa:'Jiný způsob máslového těsta',
krehke_testo_k_pastykam:'Křehké těsto k paštykám',
maslove_pasticky_s_koroptvemi:'Máslové pastičky s koroptvemi',
maslove_testo_k_pastykam:'Máslové těsto k paštykám',
pasticky_mozeckove:'Pastičky mozečkové',
pasticky_sardelove:'Pastičky sardelové',
pasticky_s_brzlikem:'Pastičky s brzlíkem',
pasticky_s_parmazanskym_syrem:'Pastičky s parmazánským sýrem',
pasticky_s_telecimi_jatrami:'Pastičky s telecími játrami',
pasticky_ze_studene_teleci_pecene:'Pastičky ze studené telecí pečené',
pasticky_z_telecich_plic:'Pastičky z telecích plic',
pastyka_ze_stiky:'Paštyka ze štiky',
pastyka_ze_zajice_v_pare_varena:'Paštyka ze zajíce v páře vařená',
pastyka_z_husich_jater:'Paštyka z husích jater',
taha_pastyka_z_basy:'Tahá paštyka z basy',
teleci_pastyka_s_plackami:'Telecí paštyka s ptačkami',
tuha_pastyka_se_zajicem:'Tuhá paštyka se zajícem'
},

pecene:{
bazant_na_zvlastni_zpusob:'Bažant na zvláštní způsob',
divoka_husa_a_kachna:'Divoká husa a kachna',
holoubata_nadivana:'Holoubata nadívaná',
hovezi_pecene:'Hovězí pečeně',
husa_a_kachna:'Husa a kachna',
husa_a_kachna_nadita:'Husa a kachna naditá',
jeleni_hrbet_se_smazenou_zemlickou:'Jelení hřbet se smaženou žemličkou',
kapoun_na_zpusob_bazanta:'Kapoun na způsob bažanta',
kapoun_se_sardelemi:'Kapoun se sardelemi',
koroptve_a_bazant:'Koroptve a bažant',
krepelky:'Křepelky',
kurata_vyslanena:'Kuřata vyslaněná',
kvicaly:'Kvíčaly',
mlady_zajic:'Mladý zajíc',
podsvince:'Podsvinče',
skopova_kejta_na_zpusob_zveriny:'Skopová kejta na způsob zvěřiny',
skopova_kejta_se_zemcatky:'Skopová kejta se zemčátky',
sluky:'Sluky',
srnci_hrbet_a_kejta:'Srnčí hřbet a kejta',
teleci_kejta_nalozena_v_octe_a_korenim:'Telecí kejta naložená v octě a kořením',
teleci_kejta_na_obycejny_zpusob:'Telecí kejta na obyčejný způsob',
teleci_kejta_se_sardelemi:'Telecí kejta se sardelemi',
teleci_kejta_slaninou_prostrkana:'Telecí kejta slaninou prostrkaná',
teleci_kejta_vyslanena_s_vinem:'Telecí kejta vyslaněná, s vínem',
teleci_ledvina_s_nadivkou:'Telecí ledvina s nádivkou',
tetrev:'Tetřev',
topan_s_nadivkou:'Ťopan s nádívkou',
uzeny_hovezi_jazyk_a_sunka:'Uzený hovězí jazyk a šunka',
veprova_kejta_nalozena:'Vepřová kejta naložená',
veprova_kejta:'Vepřová kejta',
veprova_ledvina:'Vepřová ledvina',
veprovy_podbrisek_nadity:'Vepřový podbříšek naditý',
zadecek_z_beranka_nebo_kuzlete:'Zadeček z beránka nebo kůzlete',
zajic_na_jiny_zpusob:'Zajíc na jiný způsob',
zajic:'Zajíc'
},

polivky_masite:{
bila_polivka_s_rejzi_pro_6_osob:'Bílá polívka s rejží pro 6 osob',
dusena_polivka:'Dušená polívka',
hneda_silna_polivka:'Hnědá silná polívka',
jiny_rosol_polivkovy:'Jiný rosol polívkový',
krupicna_polivka_na_zpusob_krupovky:'Krupičná polívka na způsob krupovky',
krupovka:'Krupovka',
michana_chlebova_polivka:'Míchaná chlebová polívka',
polivka_hneda_s_bazantem_nejmene_pro_12_osob:'Polívka hnědá s bažantem, nejméně pro 12 osob',
polivka_hrachova:'Polívka hrachová',
polivka_chlebova:'Polívka chlebová',
polivka_jeste_s_jinou_varenou_buchtou:'Polívka ještě s jinou vařenou buchtou',
polivka_michana_ze_zelenych_veci_pro_12_osob:'Polívka míchaná ze zelených věcí pro 12 osob',
polivka_mozeckova_se_hribkami:'Polívka mozečková se hříbkami',
polivka_mozeckova_se_smazenym_hraskem:'Polívka mozečková se smaženým hráškem',
polivka_s_buchtou_v_pare_varenou:'Polívka s buchtou v páře vařenou',
polivka_s_drstkami:'Polívka s dršťkami',
polivka_se_sagem:'Polívka se ságem',
polivka_se_smazenymi_knedlickami:'Polívka se smaženými knedlíčkami',
polivka_se_strikankami:'Polívka se stříkánkami',
polivka_se_strouhankou:'Polívka se strouhankou',
polivka_se_svitecky_kapustovymi:'Polívka se svítečky kapustovými',
polivka_se_svitecky_krupicnymi:'Polívka se svítečky krupičnými',
polivka_se_svitecky_ze_zemcat:'Polívka se svítečky ze zemčat',
polivka_se_svitecky_z_veprove_pecene:'Polívka se svítečky z vepřové pečené',
polivka_se_zemcatovymi_knedlickami:'Polívka se zemčatovými knedlíčkami',
polivka_se_zemcaty_na_jiny_zpusob:'Polívka se zemčaty na jiný způsob',
polivka_se_zemcaty:'Polívka se zemčaty',
polivka_se_zemlovym_svitkem_pro_6_i_8_osob:'Polívka se žemlovým svítkem pro 6 i 8 osob',
polivka_s_jaternymi_knedlickami:'Polívka s jaternými knedlíčkami',
polivka_s_jinou_varenou_buchtou:'Polívka s jinou vařenou buchtou',
polivka_s_knedlickami_ze_slaniny_pro_8_osob:'Polívka s knedličkami ze slaniny pro 8 osob',
polivka_s_knedlickami_ze_strouhaneho_chleba:'Polívka s knedlíčkami ze strouhaného chleba',
polivka_s_knedlickami_z_hoveziho_tuku:'Polívka s knedlíčkami z hovězího tuku',
polivka_s_knedlickami_z_jehnecich_plicek:'Polívka s knedlíčkami z jehněčích plíček',
polivka_s_kraplickami_pro_6_i_8_osob:'Polívka s krapličkami pro 6 i 8 osob',
polivka_s_krupicnymi_knedlickami:'Polívka s krupičnými knedlíčkami',
polivka_smichanymi_knedlickami:'Polívka smíchanými knedlíčkami',
polivka_s_michanymi_knedlickami_s_racimi_ocasky:'Polívka s míchanými knedličkami s račími ocásky',
polivka_s_moucnymi_knedlickami:'Polívka s moučnými knedlíčkami',
polivka_s_moucnym_svitkem:'Polívka s moučným svítkem',
polivka_s_mozeckem_pro_8_osob:'Polívka s mozečkem pro 8 osob',
polivka_s_mozeckovymi_vandlickami:'Polívka s mozečkovými vandličkami',
polivka_s_nudlemi:'Polívka s nudlemi',
polivka_s_rejzovymi_knedlickami:'Polívka s rejžovými knedlíčkami',
polivka_tlucena:'Polívka tlučená',
polivka_zemlova_na_zpusob_krupovky_pro_12_osob:'Polívka žemlová na způsob krupovky pro 12 osob',
polivka_ze_zloutku_na_zpusob_krupovky:'Polívka ze žloutků na způsob krupovky',
polivka_z_houbicek_a_telecich_brzlicku:'Polívka z houbiček a telecích brzlíčků',
polivka_zluta_s_rosolem_pro_8_neb_12_osob:'Polívka žlutá s rosolem pro 8 neb 12 osob',
rejzova_polivka_s_parmazanskym_syrem:'Rejžová polívka s parmazánským sýrem',
rosol_polivkovy:'Rosol polívkový',
tlacena_polivka_na_jiny_zpusob_s_miseninkou:'Tlačená polívka na jiný způsob, s míšeninkou',
zelena_polivka_s_jarnich_bylinek:'Zelená polívka s jarních bylinek',
zluta_polivka_s_miseninkou:'Žlutá polívka s míšeninkou'
},

prichoutky_cili_asietky:{
male_rizky_ze_studene_pecene:'Malé řízky ze studené pečeně',
nadivana_cibule:'Nadívaná cibule',
neprave_musle:'Nepravé mušle',
neprave_ustrice:'Nepravé ústřice',
teleci_mozek_na_jiny_zpusob:'Telecí mozek na jiný způsob',
teleci_mozek_s_majonezovou_omackou:'Telecí mozek s majonézovou omáčkou',
teleci_mozek:'Telecí mozek',
teleci_rizky_se_sardelemi:'Telecí řízky se sardelemi',
veprove_jitrnicky_s_pivem:'Vepřové jitrničky s pivem',
zavinute_teleci_rizky:'Zavinuté telecí řízky',
zavitky_s_michaninkou:'Závitky s míchaninkou',
zemlickove_rizky_s_jaterni_duseninkou:'Žemličkové řízky s jaterní dušeninkou',
zemlicky_se_sardelovym_maslem:'Žemličky se sardelovým máslem',
zemlicky_se_sekaninkon:'Žemličky se sekaninkon'
},

pudingy:{
anglicky_puding:'Anglický puding',
jiny_puding_s_uzeninou:'Jiný puding s uzeninou',
jiny_puding_z_rejze:'Jiný puding z rejže',
jiny_zemlovy_puding__s_maraskinem:'Jiný žemlový puding  s maraskinem',
plum_puding:'Plum puding',
puding_se_sagem:'Puding se ságem',
puding_spenatovy:'Puding špenátový',
puding_s_uzeninou:'Puding s uzeninou',
puding_tvarohovy:'Puding tvarohový',
puding_z_bramboru:'Puding z bramborů',
puding_zemlovy:'Puding žemlový',
puding_z_rejze:'Puding z rejže'
},

raci_zaby_sneci_a_musle:{
dusene_zaby:'Dušené žáby',
fasirovani_raci_s_karfiolem:'Fašírovaní raci s karfiolem',
musle_na_jiny_zpusob:'Mušle na jiný způsob',
musle_s_vinem:'Mušle s vínem',
nadivani_sneci:'Nadívaní šneci',
raci_se_smetanovou_omackou:'Raci se smetanovou omáčkou',
raci_s_omackou:'Raci s omáčkou',
smazene_zaby:'Smažené žáby',
sneci_ocasky:'Šnečí ocásky',
sneci_s_kyselym_krenem:'Šneci s kyselým křenem',
sneci_s_vinni_omackou:'Šneci s vinní omáčkou',
ustrice:'Ústřice',
zaby_se_sardelemi:'Žáby se sardelemi',
zadelavane_zaby_s_petruzelkou:'Zadělávané žáby s petruželkou'
},

rozlicna_masla:{
maslo_cokoladove:'Máslo čokoládové',
maslo_ruzove:'Máslo růžové',
maslo_sardelove:'Máslo sardelové',
maslo_s_bylinkami:'Máslo s bylinkami',
maslo_zelene:'Máslo zelené',
maslo_zlate:'Máslo zlaté',
raci_maslo:'Račí máslo'
},

rozlicne_miseninky:{
miseninka_majorankova:'Míšeninka majoránková',
miseninka_majorankova_na_jiny_zpusob:'Míšeninka majoránková na jiný způsob',
miseninka_se_hribkami:'Míšeninka se hříbkami',
miseninka_z_dymiann:'Míšeninka z dymiánn',
miseninka_ze_salveje:'Míšeninka ze šalvěje'
},

rozlicne_octy:{
ocet_bylinkovy:'Ocet bylinkový',
ocet_citronovy:'Ocet citronový',
ocet_estragonovy:'Ocet estragonový',
ocet_fialkovy:'Ocet fialkový',
ocet_malinovy:'Ocet malinový',
ocet_rybizovy:'Ocet rybízový'
},

rozlicne_ryby:{
dusena_lupice:'Dušená lupice',
fasirovany_kapr_misto_hoveziho_masa:'Fašírovaný kapr místo hovězího masa',
jezek_ze_stiky:'Ježek ze štiky',
kapr_marinovany:'Kapr marinovaný',
kapr_na_cerno_jeste_na_jiny_zpusob:'Kapr na černo ještě na jiný způsob',
kapr_na_cerno:'Kapr na černo',
kapr_na_cerno_na_jiny_zpusob:'Kapr na černo na jiný způsob',
kapr_nadivany:'Kapr nadívaný',
kapr_na_modro:'Kapr na modro',
kapr_peceny_s_kyselou_smetanou:'Kapr pečený s kyselou smetanou',
kapr_rosolovany:'Kapr rosolovaný',
kapr_se_sardelemi:'Kapr se sardelemi',
kapr_se_zlutou_omackou:'Kapr se žlutou omáčkou',
kapr_smazeny:'Kapr smažený',
losos_na_modro:'Losos na modro',
losos_na_polsky_zpusob:'Losos na polský způsob',
losos_s_holandskou_omackou:'Losos s holandskou omáčkou',
losos_s_majonezovou_omackou:'Losos s majonézovou omáčkou',
lupice_s_majonezovou_omackou:'Lupice s majonézovou omáčkou',
marinovany_losos_s_aspikem:'Marinovaný losos s aspikem',
marinovany_o_uhor:'Marinovaný o uhoř',
mnici_na_modro:'Mníci na modro',
okonni_na_modro:'Okonni na modro',
okonni_s_omackou:'Okonni s omáčkou',
okouni_na_holandsky_zpusob:'Okouni na holandský způsob',
okouni_na_lehky_zpusob:'Okouni na lehký způsob',
ouhor_na_zvlastni_zpusob:'Ouhoř na zvláštní způsob',
ouhor_s_majonezovon_omackou:'Ouhoř s majonézovon omáčkou',
ovesnicky_s_omackou:'Ovesníčky s omáčkou',
pecena_lupice_se_sardelemi:'Pečená lupice se sardelemi',
pecena_stika_s_omackou:'Pečená štika s omáčkou',
pecena_vyzina:'Pečená vyzina',
pecene_rizky_z_lososa:'Pečené řízky z lososa',
peceni_mnici:'Pečení mníci',
peceny_ouhor:'Pečený ouhoř',
piskori_se_sardelemi:'Piskoři se sardelemi',
postni_aspik:'Postní aspik',
pstruhove_s_holandskou_omackou:'Pstruhové s holandskou omáčkou',
pstruhove_v_aspiku:'Pstruhové v aspiku',
pstruhove_ve_vine_vareni:'Pstruhové ve víně vaření',
puding_z_tresky:'Puding z tresky',
rosolovany_ouhor:'Rosolovaný ouhoř',
slanecky_nalozene:'Slanečky naložené',
slanecky_pecene:'Slanečky pečené',
smazena_lupice:'Smažená lupice',
smazena_stika_s_moslemi:'Smažená štika s moslemi',
smazeni_mnici:'Smažení mníci',
smazeny_ouhor:'Smažený ouhor',
stika_na_francouzsky_zpusob:'Štika na francouzský způsob',
stika_na_holandsky_zpusob:'Štika na holandský způsob',
stika_omastena:'Štika omaštěná',
stika_sardelemi_prostrkana:'Štika sardelemi prostrkaná',
stika_s_citronovou_omackou:'Štika s citronovou omáčkou',
stika_se_sardelovou_omackou:'Štika se sardelovou omáčkou',
stika_s_knedlickami:'Štika s knedlíčkami',
stika_s_kyselou_smetanou:'Štika s kyselou smetanou',
stika_s_rakami:'Štika s rakami',
stika_s_ustricemi:'Štika s ústřicemi',
studena_stika_s_aspikem:'Studená štika s aspikem',
sumec_marinovany:'Sumec marinovaný',
sumec_peceny:'Sumec pečený',
treska_na_holandsky_zpusob:'Treska na holandský způsob',
treska_omastena_s_krenem:'Treska omaštěná s křenem',
treska_se_sardelemi:'Treska se sardelemi',
treska_s_horcicovou_omackou:'Treska s horčicovou omáčkou',
treska_smazena:'Treska smažená',
treska_s_omackou_na_jiny_zpusob:'Treska s omáčkou na jiný způsob',
treska_s_omackou:'Treska s omáčkou',
uzena_ryba:'Uzená ryba',
uzeny_losos_v_papiru_peceny:'Uzený losos v papíru pečený',
varena_lupice:'Vařená lupice',
vydra_po_vidensku:'Vydra po vídeňsku',
vyzina_s_muslemi:'Vyzina s mušlemi'
},

rybi_a_postni_polivky:{
bila_rybi_polivka:'Bílá rybí polívka',
cockova_polivka:'Čočková polívka',
druha_miseninka:'Druhá míšeninka',
dusena_polivka_s_postni_miseninkou:'Dušená polívka s postní míšeninkou',
hneda_rybi_polivka_s_knedlickami:'Hnědá rybí polívka s knedlíčkami',
hrachova_polivka:'Hrachová polívka',
hrachova_polivka_se_sviteckami:'Hrachová polívka se svítečkami',
krupicna_polivka:'Krupičná polívka',
obycejna_rybi_polivka:'Obyčejná rybí polívka',
petruzelova_voda:'Petruželová voda',
pivni_polivka:'Pivní polívka',
pivni_polivka_s_chlebem:'Pivní polívka s chlebem',
polivka_s_michanymi_knedlickami:'Polívka s míchanými knedlíčkami',
polivka_z_cerstvych_hribku:'Polívka z čerstvých hříbků',
polivka_ze_sneku:'Polívka ze šneků',
polivka_ze_suchych_hub:'Polívka ze suchých hub',
polivka_ze_syrovatky:'Polívka ze syrovátky',
polivka_ze_zab:'Polívka ze žab',
polivka_z_jarnich_bylinek:'Polívka z jarních bylinek',
polivka_z_kapra_na_zpusob_jaternicove:'Polívka z kapra na způsob jaternicové',
polivka_z_linu_na_zpusob_hovezi:'Polívka z línů na způsob hovězí',
polivka_z_raku:'Polívka z raků',
polivka_z_rozlicnych_korinku:'Polívka z rozličných kořínků',
prvni_miseninka:'První míšeninka',
sparglova_polivka_se_svitkem:'Šparglová polívka se svítkem',
treti_miseninka:'Třetí míšeninka',
vinni_polivka:'Vinní polívka',
zemcatova_polivka:'Zemčatová polívka',
zemlova_polivka_na_zpusob_krupovky:'Žemlová polívka na způsob krupovky',
zlata_polivka_s_rosolem:'Zlatá polívka s rosolem'
},

salaty:{
hlavkovy_salat_na_francouzsky_zpusob:'Hlávkový salát na francouzský způsob',
hlavkovy_salat_se_slaninou:'Hlávkový salát se slaninou',
hlavkovy_salat_s_kyselou_smetanou:'Hlávkový salát s kyselou smetanou',
michany_salat:'Míchaný salát',
michany_zemcatovy_salat:'Míchaný zemčatový salát',
obycejny_zemcatovy_salat_se_slaneckem:'Obyčejný zemčatový salát se slanečkem',
okurkovy_salat_s_kyselou_smetanou:'Okurkový salát s kyselou smetanou',
salat_celerovy:'Salát celerový',
salat_hlavkovy:'Salát hlávkový',
salat_okurkovy:'Salát okurkový',
salat_rerichovy:'Salát řeřichový',
salat_vlasky:'Salát vlaský',
salat_z_andivie:'Salát z andivie',
salat_zelny:'Salát zelný',
salat_ze_sneku:'Salát ze šneků',
salat_ze_sparglu:'Salát ze šparglu',
salat_ze_syroveho_masa:'Salát ze syrového masa',
salat_ze_syroveho_zeli:'Salát ze syrového zelí',
salat_z_chmelicku:'Salát z chmelíčku',
sladky_salat:'Sladký salát'
},

sladke_rosoly:{
ananasovy_rosol_se_smetanovou_penou:'Ananasový rosol se smetanovou pěnou',
bily_mandlovy_rosol:'Bílý mandlový rosol',
cisteni_cukru:'Čistění cukru',
cisteni_vyziho_mechyre:'Čistění vyzího měchýře',
cisteni_zelatynu:'Čistění želatýnu',
citronovy_rosol_se_smetanovou_penou:'Citronový rosol se smetanovou pěnou',
cokoladovy_rosol_se_smetanovou_penou:'Čokoládový rosol se smetanovou pěnou',
jahodovy_rosol_se_smetanovou_penou:'Jahodový rosol se smetanovou pěnou',
jiny_pomerancovy_rosol:'Jiný pomerančový rosol',
kavovy_rosol_se_smetanovou_penou:'Kávový rosol se smetanovou pěnou',
maraskynovy_rosol_se_smetanovou_penou:'Maraskýnový rosol se smetanovou pěnou',
merunkovy_rosol_se_smetanovou_penou:'Meruňkový rosol se smetanovou pěnou',
merunky_v_rosolu:'Meruňky v rosolu',
michany_rosol:'Míchaný rosol',
misenska_jablka_v_rosolu:'Míšeňská jablka v rosolu',
rejzovy_rosol_se_smetanovou_penou:'Rejžový rosol se smetanovou pěnou',
rosol_ananasovy:'Rosol ananasový',
rosol_citronovy:'Rosol citronový',
rosol_fialkovy:'Rosol fialkový',
rosol_jahodovy:'Rosol jahodový',
rosol_malinovy:'Rosol malinový',
rosol_pomerancovy:'Rosol pomerančový',
rosol_punsovy:'Rosol punšový',
rosol_rerichovy:'Rosol řeřichový',
rosol_rybizovy:'Rosol rybízový',
rosol_visnovy:'Rosol višňový',
rosol_vselikych_barev:'Rosol všelikých barev',
rosol_z_cokolady:'Rosol z čokolády',
rosol_z_kavy:'Rosol z kávy',
rosol_z_liskovych_orisku_se_smetanovou_penou:'Rosol z lískových oříšků se smetanovou pěnou',
rosol_z_vanilie:'Rosol z vanilie',
rosol_z_vina:'Rosol z vína',
smetanova_pena:'Smetanová pěna',
studene_sodo_s_rumem:'Studené šodó s rumem',
vanilovy_rosol_se_smetanovou_penou:'Vanilový rosol se smetanovou pěnou',
visne_v_rosolu:'Višně v rosolu',
},

smazeniny_pofezky_svitky_a_kotletky:{
fasirovane_karbanatky:'Fašírované karbanátky',
jehneci_kotletky:'Jehněčí kotletky',
jehneci_kotletky_nadivane:'Jehněčí kotletky nadívané',
jelitka_z_husi_krve:'Jelítka z husí krve',
jine_fasirovane_karbanatky:'Jiné fašírované karbanátky',
klobasa:'Klobása',
klobasky_z_mozecku:'Klobásky z mozečku',
michane_karbanatky_s_kapustou:'Míchané karbanátky s kapustou',
mozeckem_nadivane_zemlicky:'Mozečkem nadívané žemličky',
nadivane_teleci_rizky:'Nadívané telecí řízky',
smazena_holoubata:'Smažená holoubata',
smazena_jatra:'Smažená játra',
smazena_kuratka:'Smažená kuřátka',
smazene_krupky_z_teleciho_hrudi:'Smažené křupky z telecího hrudí',
smazene_kuzlatko:'Smažené kůzlátko',
smazene_teleci_nozicky:'Smažené telecí nožičky',
smazene_teleci_rizky:'Smažené telecí řízky',
smazene_teleci_usi_s_brzlikem:'Smažené telecí uši s brzlíkem',
smazene_vemeno:'Smažené vemeno',
smazeny_teleci_mozek:'Smažený telecí mozek',
svitecky_z_teleciho_mozku:'Svítečky z telecího mozku',
svitek_z_jater:'Svítek z jater',
svitek_z_okruzi:'Svítek z okruží',
svitek_z_teleci_ledvinky:'Svitek z telecí ledvinky',
teleci_karbanatky_cili_kotletky:'Telecí karbanátky čili kotletky',
tytez_kotletky_na_jiny_zpusob:'Tytéž kotletky na jiný způsob',
veprove_fasirovane_karbanatky:'Vepřové fašírované karbanátky',
veprove_kotletky:'Vepřové kotletky',
zavitky_z_kapusty:'Závitky z kapusty'
},

vejce:{
michane_vejce:'Míchané vejce',
michane_vejce_se_hribkami:'Míchané vejce se hříbkami',
michane_vejce_se_sardelemi:'Míchané vejce se sardelemi',
michane_vejce_s_rakami_a_sparglem:'Míchané vejce s rakami a šparglem',
nadivane_vejce:'Nadívané vejce',
nadivane_vejce_na_jiny_zpusob:'Nadívané vejce na jiný způsob',
nadivane_vejce_s_rakami:'Nadívané vejce s rakami',
sazene_vejce_se_sardelemi:'Sazené vejce se sardelemi',
smazene_vejce_s_horcici:'Smažené vejce s hořčici',
svitek_z_vajec_s_houbami:'Svítek z vajec s houbami',
vejce_na_francouzsky_zpusob:'Vejce na francouzský způsob',
vejce_na_kyselo:'Vejce na kyselo',
vejce_se_sladkou_smetanou:'Vejce se sladkou smetanou',
vejce_s_houbami:'Vejce s houbami',
vejce_s_kyselou_smetanou:'Vejce s kyselou smetanou',
vejce_s_okurkami:'Vejce s okurkami',
ztracene_vejce:'Ztracené vejce'
},

zadelavana_a_dusena_jidla:{
drstky:'Dršťky',
fasirovana_kachna:'Fašírovaná kachna',
fasirovana_kejta:'Fašírovaná kejta',
fasirovana_kejta_s_bilou_omackou:'Fašírovaná kejta s bílou omáčkou',
fasrovana_kejta_z_veproveho_masa:'Fašrovaná kejta z vepřového masa',
holoubata_dusena:'Holoubata dušená',
holoubata_s_bilou_omackou:'Holoubata s bílou omáčkou',
hrasky_nebo_jablka_z_teleciho_masa:'Hrášky nebo jablka z telecího masa',
husi_drubky_s_knedlickami:'Husí drůbky s knedlíčkami',
husi_drubky_s_nudlemi:'Husí drůbky s nudlemi',
husi_jatra_dusena:'Husí játra dušená',
jehneci_hrudicko_se_spanhelskymi_ptacky:'Jehněčí hrudičko se špaňhelskými ptáčky',
jehneci_kotletky_s_omackou:'Jehněčí kotletky s omáčkou',
jehneci_nebo_skopova_kejta_s_kyselou_smetanou:'Jehněčí nebo skopová kejta s kyselou smetanou',
kapoun_se_snekama:'Kapoun se šnekama',
kapoun_s_lanyzemi:'Kapoun s lanýžemi',
kapoun_s_muslemi:'Kapoun s mušlemi',
kapoun_s_ouhorem:'Kapoun s ouhořem',
karafa_s_karfiolem_hribkami_a_racimi_ocasky:'Karafa s karfiolem, hříbkami a račími ocásky',
knedliky_z_telecich_jater:'Knedlíky z telecích jater',
kurata_na_spesny_zpusob:'Kuřata na spěšný způsob',
kurata_na_turecky_zpusob:'Kuřata na turecký způsob',
kurata_nebo_kapouni_fasirovani:'Kuřata nebo kapouni fašírovaní',
kurata_s_celerem:'Kuřata s celerem',
kurata_s_cernou_omackou:'Kuřata s černou omáčkou',
kurata_se_hribkami:'Kuřata se hříbkami',
kurata_se_sparglovymi_hlavickami:'Kuřata se šparglovými hlavičkami',
kurata_se_zampionami:'Kuřata se žampionami',
kurata_se_zlutou_omackou:'Kuřata se žlutou omáčkou',
kurata_s_knedlickami:'Kuřata s knedlíčkami',
kurata_s_kyselou_smetanou:'Kuřata s kyselou smetanou',
kurata_s_lanyzemi:'Kuřata s lanýžemi',
kurata_s_majonezovou_omackou:'Kuřata s majonézovou omáčkou',
kurata_s_omackou_z_rajskych_jablek:'Kuřata s omáčkou z rajských jablek',
kurata_s_paprikou:'Kuřata s paprikou',
kurata_s_racim_konsume:'Kuřata s račím konsumé',
kurata_s_rejzi:'Kuřata s rejží',
miseninka_s_bilym_okolkem:'Míšeninka s bílým okolkem',
miseninka_z_drobnustek_od_drubeze_a_z_kukecich_hrebinku:'Míšeninka z drobnůstek od drůbeže a z kuřecích hřebínků',
miseninka_ze_studene_pecene:'Míšeninka ze studené pečeně',
miseninka_ze_zajice_a_sardeli:'Míšeninka ze zajíce a sardelí',
miseninka_z_hovezich_chamu_brzliku_a_racich_ocasku:'Míšeninka z hovězích chámů, brzlíků a račích ocásků',
miseninka_z_hovezich_chamu_z_ledvinky_a_vemena:'Míšeninka z hovězích chamů, z ledvinky a vemena',
miseninka_z_teleciho_srdce_a_plic:'Míšeninka z telecího srdce a plic',
miseninka_z_telecich_usi_brzliku_a_jazyku:'Míšeninka z telecích uši, brzlíků a jazyků',
nadivane_jehneci_hrndicko_s_rakami:'Nadívané jehněčí hrndičko s rakami',
nadivane_zemlicky:'Nadívané žemličky',
predni_ctvrtka_kuzlete_s_citronovou_omackou:'Přední čtvrtka kůzlete s citronovou omáčkou',
predni_ctvrtka_kuzlete_se_sparglem_a_smrzemi:'Přední čtvrtka kůzlete se šparglem a smržemi',
pul_teleci_kejty_dusene:'Půl telecí kejty dušené',
sekanina_z_teleci_pecene:'Sekanina z telecí pečeně',
sekanina_z_vemena:'Sekanina z vemena',
skopove_hrudi_dusene:'Skopové hrudí dušené',
skopove_hrudi_se_smetanou:'Skopové hrudí se smetanou',
skopove_jazyky_s_citronovou_omackou:'Skopové jazyky s citronovou omáčkou',
skopove_ledvinky_dusene:'Skopové ledvinky dušené',
skopove_maso_se_snekovou_omackou:'Skopové maso se šnekovou omáčkou',
skopove_maso_s_majorankovou_omackou:'Skopové maso s majoránkovou omáčkou',
slepice_s_citronovou_omackou:'Slepice s citronovou omáčkou',
spanhelske_ptacky:'Špaňhelské ptáčky',
teleci_brzliky_dusene:'Teleci brzlíky dušené',
teleci_hlavicka_s_frykasem:'Telecí hlavička s frykasem',
teleci_hlavicka_s_hnedou_omackou:'Telecí hlavička s hnědou omáčkou',
teleci_hradi_dusene:'Telecí hradí dušené',
teleci_hrudi_nadivane:'Telecí hrudí nadívané',
teleci_hrudi_pecene_s_omackou:'Telecí hrudí pečené s omáčkou',
teleci_hrudi_s_maslemi:'Telecí hrudí s mašlemi',
teleci_hrudi_s_vinni_omackou:'Telecí hrudí s vinní omáčkou',
teleci_hrudi_vyslanene:'Telecí hrudí vyslaněné',
teleci_jatra_dusena:'Telecí játra dušená',
teleci_kejta_s_celerovou_omackou:'Telecí kejta s celerovou omáčkou',
teleci_kejta_se_smetanou:'Telecí kejta se smetanou',
teleci_kejticka:'Telecí kejtička',
teleci_maso_dusene:'Telecí maso dušené',
teleci_maso_s_kminem:'Telecí maso s kmínem',
teleci_okruzi_se_smetanou:'Telecí okruží se smetanou',
teleci_okruzi_s_frykasem:'Telecí okruží s frykasem',
teleci_osrdi_pecene:'Telecí osrdí pečené',
teleci_plice_na_jiny_zpusob:'Telecí plíce na jiný způsob',
teleci_plice:'Telecí plíce',
teleci_rizky_se_sardelemi:'Telecí řízky se sardelemi',
teleci_rizky_se_smrzemi:'Telecí řízky se smržemi',
teleci_rizky_s_kaprlemi:'Telecí řízky s kaprlemi',
teleci_rizky_s_kyselou_smetanou_na_jiny_zpusob:'Telecí řízky s kyselou smetanou na jiný způsob',
teleci_rizky_s_kyselou_smetanou:'Telecí řízky s kyselou smetanou',
teleci_rizky_s_paprikou:'Telecí řízky s paprikou',
teleci_rizky_s_vinem:'Telecí řízky s vínem',
teleci_rizky_ze_studene_pecene:'Telecí řízky ze studené pečeně',
teleci_srdce_a_brzlik:'Telecí srdce a brzlík',
veprova_hlava:'Vepřová hlava',
veprove_maso_na_pive:'Vepřové maso na pivě',
zadelavane_kuzle:'Zadělávané kůzle',
zadelavane_vemeno:'Zadělávané vemeno',
zavinute_teleci_rizky:'Zavinuté telecí řízky'
},

zadelavana_zverina:{
cerna_zverina:'Černá zvěřina',
cerna_zverina_na_jiny_zpusob:'Černá zvěřina na jiný způsob',
divoka_kachna:'Divoká kachna',
duseni_bazanti:'Dušení bažanti',
duseni_skrivanci:'Dušení skřivánci',
duseny_tetrev:'Dušený tetřev',
karbanatky_z_bazantu_neb_koroptvi:'Karbanátky z bažantů neb koroptví',
karbanatky_ze_zajice:'Karbanátky ze zajíce',
koroptve_dusene:'Koroptve dušené',
koroptve_na_francouzsky_zpusob:'Koroptve na francouzský způsob',
koroptve_s_pomerancovou_omackou:'Koroptve s pomerančovou omáčkou',
krepelky_s_rejzi:'Křepelky s rejží',
kvicaly_s_rejzi:'Kvíčaly s rejží',
male_ptacky_s_omackou:'Malé ptáčky s omáčkou',
male_ptacky_v_zupana:'Malé ptáčky v župana',
sekaninka_z_bazantu_neb_koroptvi:'Sekaninka z bažantů neb koroptvi',
sekaninka_ze_zajice:'Sekaninka ze zajíce',
studeny_zajic_bazant_koroptve_srnci_a_jeleni_pecene:'Studený zajíc, bažant, koroptve, srnci a jeleni pečeně',
zadelane_zbytky_od_koroptvi:'Zadělané zbytky od koroptví',
zadelavane_drozdy_aneb_kvicaly:'Zadělávané drozdy aneb kvíčaly',
zadelavane_sluky:'Zadělávané sluky',
zajeci_predek_na_jiny_zpusob:'Zaječí předek na jiný způsob',
zajeci_predek_zadelany_na_cerno:'Zaječí předek zadělaný na černo',
zverina_s_jalovcovou_omackou:'Zvěřina s jalovcovou omáčkou',
zverina_srnci_zadelavana:'Zvěřina srnci zadělávaná'
},

zavarene_cele_ovoce:{
citronada_v_cukru_zavarena:'Citronáda v cukru zavařená',
jak_se_ovoce_v_pare_zavaruje:'Jak se ovoce v páře zavařuje',
merunky_v_cukru_zavarene:'Meruňky v cukru zavařené',
mirabelky_a_zelencata_v_cukru_zavarene:'Mirabelky a zelenčata v cukru zavařené',
orechy_v_cukru_zavarene:'Ořechy v cukru zavařené',
rybiz_v_octe_nalozeny:'Rybíz v octě naložený',
sipky_v_cukru_zavarene:'Šípky v cukru zavařené',
visne_v_cukru_zavarene:'Višně v cukru zavařené',
visne_v_octe_nalozene:'Višně v octě naložené',
zavarena_gdoulova_jablka:'Zavařená gdoulová jablka',
zavarene_fiky:'Zavařené fíky',
zavarene_muskatove_hrusticky:'Zavařené muškátové hruštičky',
zavarene_vinni_zrni:'Zavařené vinní zrní',
zavareny_ananas:'Zavařený ananas',
zavareny_angrest:'Zavařený angrešt',
zavareny_meloun:'Zavařený meloun',
zavareny_rybiz:'Zavařený rybíz'
},

zeleniny:{
articoky_dusene:'Artičoky dušené',
articoky_s_omackou:'Artičoky s omáčkou',
brukve_nadivane:'Brukve nadívané',
brukve_s_jehnecim_masem:'Brukve s jehněčím masem',
cocka:'Čočka',
hlavkovy_salat_nadivany:'Hlávkový salát nadívaný',
hrach:'Hrách',
hrach_promackany:'Hrách promačkaný',
jina_michaninka_pro_8_i_12_osob:'Jiná míchaninka pro 8 i 12 osob',
kadernik_s_klobasou:'Kadeřník s klobásou',
kapusta_fasirovana_na_jiny_zpusob:'Kapusta fašírovaná na jiný způsob',
kapusta_fasirovana_pro_8_osob:'Kapusta fašírovaná pro 8 osob',
kapusta_krajena:'Kapusta krájená',
kapusta_nadivana:'Kapusta nadívaná',
kapusta_s_karbanatkami:'Kapusta s karbanátkami',
kapusta_s_rejzi_v_pare_varena:'Kapusta s rejži v páře vařená',
kapusta_s_uzenym_jazykem_v_pare_varena:'Kapusta s uzeným jazykem v páře vařená',
kapustova_poupata_s_rakami:'Kapustová poupata s rakami',
karfiol_omasteny:'Karfiol omaštěný',
karfiol_s_kuratkami:'Karfiol s kuřátkami',
karfiol_ve_fasi_pro_8_osob:'Karfiol ve faši pro 8 osob',
karfiol_v_kremu_pro_8_osob:'Karfiol v krému pro 8 osob',
kolnik_s_kastanami:'Kolník s kaštanami',
kolnik_s_veprovym_masem:'Kolník s vepřovým masem',
kysele_zeli_pecene:'Kyselé zelí pečené',
kysele_zeli_s_veprovou_pecinkou:'Kyselé zelí s vepřovou pečínkou',
mesicne_retkvicky:'Měsíčné řetkvičky',
michaninka_ze_zelenin:'Míchaninka ze zelenin',
mrkev_se_smazenym_vemenem:'Mrkev se smaženým vemenem',
mrkev_s_kastanami:'Mrkev s kaštanami',
nadivane_okurky:'Nadívané okurky',
repa_s_veprovym_masem:'Řepa s vepřovým masem',
sladke_zeli_fasfrovane:'Sladké zelí fasfrované',
spargl_na_zpusob_zeleneho_hrasku:'Špargl na způsob zeleného hrášku',
spargl:'Špargl',
spenat_se_smazenymi_nozickami:'Špenát se smaženými nožičkami',
spenat_ve_forme:'Špenát ve formě',
stovik_se_smazenymi_jatrami:'Šťovík se smaženými játrami',
vodnice_na_kyselo:'Vodnice na kyselo',
vodnice_nalozena:'Vodnice naložená',
vodnice:'Vodnice',
zelene_boby_s_jehnecim_masem:'Zelené boby s jehněčím masem',
zeleny_hrasek_se_smazenymi_kuraty:'Zelený hrášek se smaženými kuřaty',
zeleny_hrasek_s_mrkvickou:'Zelený hrášek s mrkvičkou'
},

zmrzliny:{
jahodova_zmrzlina_se_smetanou:'Jahodová zmrzlina se smetanou',
jak_se_cukr_cisti_a_ve_vareni_postupuje:'Jak se cukr čistí a ve vaření postupuje',
jak_se_ma_led_pripravovat_a_zmrzlina_delat:'Jak se má led připravovat a zmrzlina dělat',
zmrzlina_ananasova:'Zmrzlina ananasová',
zmrzlina_cokoladova:'Zmrzlina čokoládová',
zmrzlina_s_maraskynem:'Zmrzlina s maraskýnem',
zmrzlina_z_caje:'Zmrzlina z čaje',
zmrzlina_z_citronu:'Zmrzlina z citronu',
zmrzlina_z_horkych_mandli:'Zmrzlina z hořkých mandli',
zmrzlina_z_jahod:'Zmrzlina z jahod',
zmrzlina_z_kastanu:'Zmrzlina z kaštanů',
zmrzlina_z_kavy:'Zmrzlina z kávy',
zmrzlina_z_liskovych_orisku:'Zmrzlina z lískových oříšků',
zmrzlina_z_malin:'Zmrzlina z malin',
zmrzlina_z_paleneho_cukru:'Zmrzlina z páleného cukru',
zmrzlina_z_pomerancu:'Zmrzlina z pomerančů',
zmrzlina_z_punce:'Zmrzlina z punče',
zmrzlina_z_rybizu:'Zmrzlina z rybízu',
zmrzlina_z_vanilie:'Zmrzlina z vanilie',
zmrzlina_z_visni:'Zmrzlina z višní'
},

miry_a_vahy:{
koflicek:'Koflíček',
kvintlik:'Kvintlík',
libra:'Libra',
lot:'Lot',
zejdlik:'Žejdlík'
}
}
